### PR TITLE
Add support for git repositories accessible only by ssh keys[Shorter version]

### PR DESCRIPTION
**Pull request by zakariazh**
Hi, 

I propose this modification to add support for git accessible only by SSH. (no web acces) like : git@url:path/to/repo to fix this error : 
```
Failed validating 'pattern' in schema['properties']['sources']['items']['properties']['url']:
    {'pattern': '^(https?|ssh|git)://.*$', 'type': 'string'}
```
Thank you

### CODE REVIEW

**Comment by pboettch** [comment]
Your `git@host:repo`-URL is actually a shorter/alternative version of `ssh://git@host/repo`-URL. I think we would prefer to keep scheme-based-URLs as a requirement. 

But if you have good arguments this can be reconsidered.

**Comment by zakariazh** [comment]
thank you for your reply
Effectively, the modification adds support for this types of URL. We may have to change a lot of URLs to migrate to cooker from another projects (in this case). We can change the URLs by many methods but the easiest is to integrate it into cooker. I think support for such kind of link format is still useful for the project (as long as the link is working elsewhere it will be good if cook the support as well)

**Comment by boucman** [comment]
Alternatively, could the message be made more clear ?

When cloning from github (for example) with ssh, only the short form is provided and I guess lots of people don't know that there is an implicit ssh:// in the git@ form...

**Comment by zakariazh** [comment]
> When cloning from github (for example) with ssh, only the short form is provided and I guess lots of people don't know that there is an implicit ssh:// in the git@ form...

I think that's a very good reason too. Thank you.

**Comment by pboettch** [comment]
OK, convinced, for me matching `user@host:repo/path.git` and assuming it is a git-repo (ie. can be passes to git clone) is OK. Without the .git-suffing it should fail.

What do you think?

For merging we need a test-case, the schema update and maybe a change in the cooker-source to use the git-checkout-code in of a .git-repo.

**Comment by zakariazh** [comment]
Hi,
I added a qemux86-warrior-menu-short-ssh.json file with url to download meta-openembedded over SSH as a test example. I think the source code for cooker does not need to be modified.

What do you think @pboettch ?

**Comment by cpb-** [comment]
Hi @zakariazh, thank you for this patch!
I can't really test it these days, but it seems ok for me.
Are you ok @pboettch ?

**Comment by pboettch** [comment]
I will integrate your changes add a test and do some modifications to the schema. Having only one url-validator will become too complicated if we add more supported URLs.

**Comment by pboettch** [comment]
Integrated manually. Thanks for your contribution!

**Pull request closed without merging**
